### ISSUE TITLE
Do you have any quantitative results such as FID?

### ISSUE THREAD

**Issue by csyanbin** [eifuentes/swae-pytorch#9]
Hi, thanks so much for the pytorch implementation of SWAE.

By the way, do you have any results such as FID score?

**Comment by eifuentes** [comment]
hi @csyanbin, I would reference the original paper in the README for more information but since no FID score was shown I did not go ahead and implement any myself. The lsun results in the README I did for my own learning, it is outside the scope of the original paper.
